services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: millennium
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src/public:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/snippets:/etc/nginx/snippets
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8.2-fpm
    container_name: php-fpm
    volumes:
      - ./src:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_NAME=millennium
      - DB_USER=user
      - DB_PASSWORD=password
    command: >
      bash -c "docker-php-ext-install pdo_mysql && php-fpm"
    depends_on:
      - mysql
networks:
  app-network:
    driver: bridge